In [1]:
import pandas as pd

## read files

In [52]:
from  datetime import datetime
from datetime import date

In [8]:
fb =pd.read_csv("temp_datalab_records_social_facebook.zip", compression="zip")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## FAcebook

In [70]:
fb.info() # info about the data fram

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3621391 entries, 0 to 3621390
Data columns (total 14 columns):
dataset_id             int64
time                   object
username               object
checkins               int64
has_added_app          object
were_here_count        int64
likes                  int64
talking_about_count    int64
facebook_id            int64
date_added             object
date_updated           object
entity_id              float64
cusip                  float64
isin                   float64
dtypes: float64(3), int64(6), object(5)
memory usage: 386.8+ MB

In [71]:
fb.columns

Index(['dataset_id', 'time', 'username', 'checkins', 'has_added_app',
       'were_here_count', 'likes', 'talking_about_count', 'facebook_id',
       'date_added', 'date_updated', 'entity_id', 'cusip', 'isin'],
      dtype='object')

In [72]:
fb.head()

,dataset_id,time,username,checkins,has_added_app,were_here_count,likes,talking_about_count,facebook_id,date_added,date_updated,entity_id,cusip,isin
0,53088,2015-01-01 05:00:00+00,SodaStream,0,f,0,761533,587,54885616308,NaN,2017-02-14 03:35:13.236826+00,NaN,NaN,NaN
1,52642,2015-01-01 05:00:00+00,ANSYSInc,148,f,0,43442,1305,160242297413411,NaN,2017-02-14 01:55:52.78506+00,NaN,NaN,NaN
2,53656,2015-01-01 05:00:00+00,MyAquaAmerica,0,f,0,5591,297,591693544195818,NaN,2017-02-14 08:13:51.267343+00,NaN,NaN,NaN
3,53033,2015-01-01 05:00:00+00,Qualcomm,173,f,0,1232521,2685,108472637291,NaN,2017-02-14 03:24:04.363035+00,NaN,NaN,NaN
4,52783,2015-01-01 05:00:00+00,eaglepharmaceuticals,0,f,0,18,0,1428265940729350,NaN,2017-02-14 02:22:10.193588+00,NaN,NaN,NaN

In [86]:
fb["username"].value_counts().sort_values(ascending=False)

aflacduck                     1222
RedRobin                      1222
2u                            1222
SPG                           1222
shutterfly                    1222
TiVo                          1222
ModelNInc                     1222
stamps.com                    1221
MercBank                      1221
telenav                       1221
atmosenergy                   1221
EchoStar                      1221
ford                          1221
gopro                         1221
GrandCanyonU                  1221
SynacorInc                    1221
MurphyUSA                     1221
ApacheCorporation             1221
BancorpSouthStudents          1221
Costco                        1221
lumberliquidators             1221
petropoints                   1221
MicrovisionInc                1221
ZoesKitchen                   1221
merrimackpharma               1221
SodaStream                    1221
ColumbiaSportswear            1221
travelers                     1221
generalmotors                 1221
CDWCorporation                1221
                              ...
OneKBR                           3
BrinksHomeSec                    3
gerdau                           2
KBRcorp                          2
cbssportingclub                  2
LeeRiders                        2
Verizonfios                      2
DiscoveryCove                    2
nteloswireless                   2
thoughtcocom                     2
InterGlobeTechnologies           2
TKMaxxAustria                    2
CambrexCorporation               2
AviancaCo                        2
ncmmedianetworks                 1
BuschGardensVa                   1
GlobalPayInc                     1
mclartynissannlr                 1
blackanddecker                   1
corporateexecutiveboard          1
MobankKC                         1
ExperimentswithGoogle            1
Lasuavecita104.3                 1
mclartymazda                     1
mclartynissanlr                  1
AlexanderMarineSD                1
InvesetmentTechnologyGroup       1
VivintSolarAlbany                1
Lifetime.Life                    1
AmericanNationalHomeOffice       1
Name: username, Length: 4950, dtype: int64

In [90]:
fb["time"][0] #  see the format of the time

'2015-01-01 05:00:00+00'

In [99]:
#extract year , month and date
def get_year_mon_day(date):
    date= str(date) # convert to string 
    splited= date.split("-") # to get month, day, and year and time
    year= splited[0] # get year 
    month=splited[1]
    day= splited[2][:2] # extract only the day
    return year, month ,day

In [118]:
def get_year(date):
    date= str(date) # convert to string 
    splited= date.split("-") # to get month, day, and year and time
    year= splited[0] # get year 
    return year

def get_month(date):
    date= str(date) # convert to string 
    splited= date.split("-") # to get month, day, and year and time
    month= splited[1] # get year 
    return month
def get_day(date):
    date= str(date) # convert to string 
    splited= date.split("-") # to get month, day, and year and time
    day= splited[2][:2] # extract only the day, month ,day
    return day

In [103]:
a,b, c=get_year_mon_day(fb["time"][0])
b

'01'

In [ ]:
get_year_mon_day(fb["time"][0])

In [111]:
fb["time"].apply(get_year_mon_day).values

array([('2015', '01', '01'), ('2015', '01', '01'), ('2015', '01', '01'),
       ..., ('2018', '07', '17'), ('2018', '07', '17'),
       ('2018', '07', '17')], dtype=object)

In [120]:
# add year, month and day collumns extracted from time column
fb["Year"]= fb["time"].apply(get_year)

In [121]:
fb["Month"]= fb["time"].apply(get_month)
fb["Day"]=fb["time"].apply(get_day)

In [122]:
fb.columns # columns added

Index(['dataset_id', 'time', 'username', 'checkins', 'has_added_app',
       'were_here_count', 'likes', 'talking_about_count', 'facebook_id',
       'date_added', 'date_updated', 'entity_id', 'cusip', 'isin', 'Year',
       'Month', 'Day'],
      dtype='object')

In [123]:
fb["Year"].unique()

array(['2015', '2016', '2017', '2018'], dtype=object)

In [ ]:
matplotlib.pyplot

In [87]:
fb["time"].nunique(

1241

In [88]:
fb.corr()

,dataset_id,checkins,were_here_count,likes,talking_about_count,facebook_id,entity_id,cusip,isin
dataset_id,1.000000,0.014284,-0.033538,-0.047131,-0.031880,0.117912,NaN,NaN,NaN
checkins,0.014284,1.000000,0.166944,0.052411,0.038259,-0.020870,NaN,NaN,NaN
were_here_count,-0.033538,0.166944,1.000000,0.256956,0.065495,0.077585,NaN,NaN,NaN
likes,-0.047131,0.052411,0.256956,1.000000,0.358866,0.039388,NaN,NaN,NaN
talking_about_count,-0.031880,0.038259,0.065495,0.358866,1.000000,-0.037722,NaN,NaN,NaN
facebook_id,0.117912,-0.020870,0.077585,0.039388,-0.037722,1.000000,NaN,NaN,NaN
entity_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cusip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
datetime.strptime("2015-01-01","%Y, %m, %d")

ValueError: time data '2015-01-01' does not match format '%Y, %m, %d'

In [78]:
"{%Y}".format(datetime.date(2015-01-01 05:00:00+00))

TypeError: descriptor 'date' requires a 'datetime.datetime' object but received a 'str'

In [20]:
set(fb["username"])

{nan,
 'PT6Nation',
 'ListaInternational',
 'winnebago',
 'MedidataSolutions',
 'attbusiness',
 'vanguardengines',
 'ShopVersona',
 'SundanceTV',
 'HawaiianAirlines',
 'InfinitiTampa',
 'NeenahFinePaper',
 'MacatawaBank',
 'GoCriteo',
 'HDSupplyWhiteCap',
 'ONEOKInc',
 'SKYSITETechnologies',
 'rejuvenationlightingandhouseparts',
 'AppFolio',
 'BrinksHomeSecurity',
 'GoStorageUnits',
 'TSYS1',
 'leafchronicle',
 'AstrotechCorp',
 'hdsupplyfm',
 'Dreft',
 'ryanair',
 'PlaneTechs',
 'mosaiccompany',
 'jose945',
 'PolarisGov',
 'HouseLogic',
 'SMEnergy',
 'geffenmedical',
 'always',
 'NordsonMARCH',
 'HNNow',
 'BBVAFrancesArg',
 'Hologic',
 'gamestopsuomi',
 'WEtv',
 'WisconsinStateJournal',
 'hollister',
 'AlliedMotion',
 'gillette',
 'CCCGlobal',
 'CogginNissanAvenues',
 'merrimackpharma',
 'BRIDGENB',
 'VideojetUS',
 'PACCARFinancial',
 'pioneeres',
 'ValueLine',
 'MoviePass',
 'Chaco',
 'PerkinElmer',
 'catalystbio',
 'Lasuavecita1043',
 'AmeriSpecCorporate',
 'patcatanstores',
 'V8',
 'JoMaloneLondon',
 'AlugueTemporada',
 'Gaiam',
 'CarlisleSynTec',
 'Microsoft',
 'ISBBDO',
 'BrooksAutomationInc',
 'TheAxisAgency',
 'MYOSRENSTechnology',
 'ipower',
 'deltadownscasino',
 'southernrefrigeratedtransport',
 'TaxACT',
 'CalderCasino',
 'sidestepshoes',
 'WileyVCHVerlag',
 'AerojetRdyne',
 'FirstCitizensBankKY',
 'foreign.policy.magazine',
 'Anthropologie',
 'weightwatchers',
 'bikinidotcom',
 'Kadant',
 '1ShoppingCart',
 'wynneverett',
 'HotSpringSpas',
 'ATTCareers',
 'NissanofTampa',
 'Enquirer',
 'whirlpoolusa',
 'NordsonASYMTEK',
 'scsunnews',
 'WernerEnterprisesInc',
 'NxStage',
 'rbc',
 'Swanson',
 'SkiHeavenly',
 'GoogleSMB',
 'SteelcaseEducation',
 'TitanTireCorp',
 'ManpowerUS',
 'MaherComm',
 'AlphaAdvancedMaterials',
 'HondrosNursing',
 'daVinciSurgery',
 'LivePersonInc',
 'grainger',
 'athenahealth',
 'amctheatres',
 'MarineMaxDaytona',
 'swiffer',
 'TeradyneInc',
 'Teva',
 'surfexcelindia',
 'Toro.Company',
 'PDR.Network',
 'EPAM.Global',
 'badgermeter',
 'formeonline',
 'IFCFilmsOfficial',
 'DonnaKaranNewYork',
 'stitchfix',
 'workhorsegroup',
 'MotionInd',
 'aptitopos',
 'AmericanNationalHomeOffice',
 'footaction',
 'carefusion',
 'WhollyGuacamole',
 'SharpsCompliance',
 'Marvel',
 'ChillicotheGazette',
 'universalhealthservices',
 'DSW',
 'TeamResellerClub',
 'CatoFashions',
 'covanta',
 'thenorthface',
 'norcraftcabinetry',
 'Simonandschuster',
 'ctrip.en',
 'timesreporter',
 'EnterpriseBank',
 'GoogleGlass',
 'manhattantvseries',
 'HarteHanks',
 'Callaway',
 'POOLCORP1',
 'CTGEurope',
 'TheTownTalk',
 'proteostasis',
 'OreillyAutoParts',
 'XeroxCorp',
 'TiVo',
 'Terrain',
 'googleartsculture',
 'PepsiCo',
 'CNrail',
 'RegencyCenters',
 'realtor.com',
 'ArielDetergente',
 'BallCanning',
 'atlantiscasinoresortspa',
 'AshlandInc',
 'siebertnet',
 'EatGoodTimes',
 'KirkwoodMtn',
 'MarineMaxMinnesota',
 'smithmicro',
 'Amazon',
 'acxiomcorp',
 'Chuys.Restaurants',
 'panoplynetwork',
 'LaSaltenaArg',
 '3MCollision',
 'SpectraEnergy',
 'Sequans',
 'EagleBrand',
 'FritoLay',
 'Waverly',
 'DailyLeader',
 'GDMissionSystems',
 'MichiganInsuranceCompany',
 'Quaker',
 'FirstMerchants',
 'DrilQuipGlobal',
 'FirstBusinessBank',
 '21Club',
 'birchlane',
 'CambrexCorporation',
 'assimumabrastemp',
 'CTCAviation',
 'bolthousefarms',
 'sonoco.products',
 'foxdeportes',
 'TheTandD',
 'TransActTech',
 'RangeResourcesCorporation',
 'fox43news',
 'OffersDOTcom',
 'PurdueGlobal',
 'STMicroelectronics.NV',
 'SKYSITEdocmanagement',
 'MansfieldNewsJournal',
 'LithiaMotors',
 'heatbiologics',
 'SevernSavingsBank',
 '5StarSeniorLiving',
 'MetaWellness1',
 'bprox',
 'erosnow',
 'ESPN1650',
 'Pears',
 'HUEPPE.SHOWERANDSOUL',
 'empiretribune',
 'SiouxCityJournal',
 'esabna',
 'MIHomesInc',
 'HumminbirdElectronics',
 'cejkasearchinc',
 'Philips',
 'mresortspacasino',
 'generacresidential',
 'SikorskyAircraft',
 'newellbrands',
 'lehighoutfitters',
 'elfcosmetics',
 'NalleyINFINITIAtlanta',
 'edgewaterfullscope',
 'CourtesyPalmHarborHonda',
 'KayJewelers',
 'harristeeter',
 'LatitudesDeck',
 'propelwater',
 'AvnetInc',
 'avlcitizentimes',
 'pkpbbdo',
 'NUVOTupperware',
 'bbdoportugal',
 'EmerilsCooking',
 'ownerscom',
 'icadmed',
 'IndependentBank',
 'ymedialabsinc',
 'LiveRamp',
 'OtelcoInc',
 'kcwy13',
 'hot1035',
 'krns6',
 'timken',
 'GentexCorporation',
 'OwensCorning',
 'Marshalls',
 'NorthPointFordLincoln',
 'KCMasterpiece',
 'bettycrocker',
 'AmanaBrand',
 'Bloomingdales',
 'Allegiant',
 'VactorMfg',
 'DEVRYUNIVERSITY',
 'oxfordgolf',
 'imperva',
 'AuroraAdvertiser',
 'CarlisleCW',
 'calwater',
 'jdpower',
 'centennialbanking',
 'GNC',
 'tennessean',
 'HDFC.bank',
 'McKessonCorporation',
 'OrchardSupplyHardware',
 'HamburgReporter',
 'autopartswarehouse',
 'CUIGlobal',
 'shophouse',
 'proximitylondon',
 'ABXAirInc',
 'AmericanNationalAgribusinessInsurance',
 'newscorp',
 'EXFOInc',
 'ExploreLearningReflex',
 'statesmanjournal',
 'theoakridger',
 'TaylorDevices',
 'eatsmartveggies',
 'SevernBank',
 'mobil1',
 'glenrosereporter',
 '247Sports',
 'freestateandson',
 'premierhealthcarealliance',
 'CourtesyHyundaiTampa',
 'onegasincorporated',
 'RuthsChrisSteakHouseNational',
 'MobankKC',
 'VistaOutdoor',
 'OneKingsLane',
 'argusleader',
 'PursuitAlaska',
 'SandiaLabs',
 'southjerseyenergy',
 'Gmail',
 'dallasyachting',
 'SeaRayBoat',
 'TildaRice',
 'illuminainc',
 'ConAgraFoods',
 'silgancontainersllc',
 'LeidosInc',
 'skysiteconstructionapp',
 'ufptechnologies',
 'RevoSunglasses',
 'FactSet',
 'becca.cosmetics',
 'NEWS7',
 'FMCTI',
 'GoldfishSmiles',
 'thecapitalgrille',
 'safeguardscientifics',
 'Equifax',
 'ManhattanWGNA',
 'GTMBestPractices',
 'cubiccorporation',
 'duanereade',
 'biospacecommunity',
 'woodwardinc',
 'kic',
 'AlliantEnergyFoundation',
 'MatrixMedicalNetwork',
 'THORtravelservices',
 'reliv',
 'servicemaxinc',
 '995themountain',
 'poconorecord',
 'Ultracargo',
 'discover',
 'StevensPointJRL',
 'penumbraincmedtech',
 'UnitedHealthcare',
 'tomcatbrand',
 'pinesol',
 'AlimeraSciences',
 'bargainadvocate',
 'vonage',
 'Winners',
 'BetterOats',
 'TheCW',
 'MazorRobotics',
 'BBDOUkraine',
 'sgiglobal',
 'hertz',
 'ShawneeNewsStar',
 'publicopinionnews',
 'CTIBalloons',
 'TheSpectrumNews',
 'kolotv',
 'braunshaversus',
 'FirstMidwest',
 'DeVryEducationGroup',
 'DwellStudio',
 'bestsourcemarketing1',
 'Koss',
 'MontanaStandard',
 'BMOHarrisBank',
 'pedialyte',
 'supersavvyme',
 'YvesVeggiePage',
 'PlaySpeedyNinja',
 'AlliantEnergy',
 'ProteinSimple',
 'alliancedata',
 'santanderchile',
 'ExploreLearningGizmos',
 'gpstrategies',
 'ChemicalBankCommunity',
 'EvangelineDownsRacetrackCasino',
 'LaneBryant',
 'OmnicomGroupInc',
 'Trappeys',
 'SelectMedical',
 'MagnaInternational',
 'sportsmanswh',
 'dentonrc',
 'aboutdotcom',
 'hilton',
 'VITROAGENCY',
 'BankUnited.Official',
 'chuxproducts',
 'MDSTF',
 'RalphLauren',
 'MolecularDevices',
 'palitem',
 'mrclean',
 'MetroWestDailyNews',
 'OldDominionFreightLine',
 'NationstarMortgage',
 'GameStopItalia',
 'bbdoconnect',
 'SBOnebank',
 'grapenutscereal',
 'DoritosUSA',
 'PlayOverwatch',
 'planetfitness',
 'egglandsbesteggs',
 'TheNew1037',
 'makemytrip',
 'Coloradoan',
 'studiocitymacau',
 'globalsiliconvalley',
 'jessicasimpson',
 '23WIFR',
 'bancomacro',
 'ClearanceJobs',
 'BET',
 'ubscareers',
 'sears',
 'CogginNissanAtlantic',
 'madisongasandelectric',
 'therecordheraldwaynesboro',
 'WickedLocal',
 'lacieworldwide',
 'beef.ADM',
 'GladiatorGW',
 'shinhanlife',
 'SEMAgency',
 'randyjackson',
 'BALI.Intimates',
 'Lennox',
 'radiodotcom',
 'WestEndRoofingSupply',
 'Ferrellgas',
 'RotoRooter',
 'LifeLock',
 'columbiastatebank',
 'ApplianceSmartUS',
 'GameStop',
 'LeMarsInsurance',
 'CDWCorporation',
 'MercerInsights',
 'TelephoneandDataSystems',
 'Inseego',
 'ReginaVinegar',
 'contrapuntobbdoespana',
 'USGCORP',
 'CapellaUniversity',
 'KBSP.agency',
 'CenturyLink',
 'prinsautogassystemen',
 'FEMSA',
 'FamilyVacationCritic',
 'marronebio',
 'sobe',
 'stjamesplaindealer',
 'Teladoc',
 'dailyadvertiser',
 'randolphcountyheraldtribune',
 'Mudd',
 'SanminaCorp',
 'FyponMillwork',
 'RCJournal',
 'Centexhomes',
 'Vistaprint',
 'Enzo.Life.Sciences',
 'BellCanada',
 'PineMountainFire',
 'LandmarkNationalBank',
 'skplanet',
 'firstalertca',
 'potbellysandwichshop',
 'RavenAerostar',
 'ATTSmallBiz',
 'harvardapparatus',
 'foxchasebank',
 'VishayIntertechnology',
 'YardHouse',
 'BemisCompany',
 'bancocredichile.cl',
 'boyds',
 'RAMCOproperties.rpt',
 'SafetySignsService',
 'CTGinc',
 'Gordons',
 'tkmaxx.at',
 'cpsiehr',
 'EASbrand',
 'coastwaycommunitybank',
 'HP',
 'spokinc',
 'hawaiiantropic',
 'tractionuap',
 'EmpenoFacilMexico',
 'HowardBank1',
 'Jos.A.Bank.Clothiers.Inc',
 'aaronbrothers',
 'thinkgeek',
 'Amdocs',
 'mtssystemscorp',
 'RegisSalons',
 'GlobalSelfStorageCorporate',
 'MerryMaids',
 'microsoftbi',
 'MyNortheastBank',
 'terrachips',
 'journalandcourier',
 'mopar',
 'OceanFirstBank',
 '2u',
 'mountaindew',
 'aol',
 'RockyGap',
 'Quanterix',
 'navistar',
 'elmirastargazette',
 'theAlaskaCollection',
 'craftsman',
 'PlaytexSportandGentleGlide',
 'HollywoodMVRC',
 'MarinSoftware',
 'Skintimate',
 'MWBank',
 'L3Communications',
 'venmo',
 'secret',
 'kitchme',
 'DestinationMat',
 'cbsfilms',
 'compugraphicsphotomasks',
 'BradyCorporation',
 'ArtsWaySci',
 'DMNmediasolutions',
 'PerdigaoOficial',
 'sealymattress',
 'WD',
 'TopDressSupplements',
 'bestbuy',
 'FIStoday',
 'GoDaddy',
 'savingsinstitute',
 'withKTgroup',
 'spacelabshealthcare',
 'radiojose1011',
 'GE',
 'MedicalStaffingNetwork',
 'Costco',
 'solarcity',
 'WildcatMountain',
 'bulletin.newsroom',
 'hyvesolutions',
 'PolarisRZR',
 'jusroluk',
 'MessengerPostMedia',
 'WABCOvehiclecontrolsystems',
 'kellyservices',
 'HollywoodTunica',
 'NalleyINFINITIMarietta',
 'RedRobin',
 'concordwatches',
 'YouPuissantNaturellement',
 'mediasite',
 'Aonplc',
 'UnitedFireGroup',
 'HarleyDavidsonFootwear',
 'OverlandStorage',
 'carowindspark',
 'Jose107.1',
 'VisianICL',
 'Pierce',
 'cynthiarowleyny',
 'HormelHealthLabs',
 'schwinnfitness',
 'EverfreshJuice',
 'thehuddle',
 'NeonodeTechnologies',
 'SharpSpringInc',
 'StellarBiotech',
 'Bowflex',
 'ProudToBeGenpact',
 'palacestation',
 'CelticHealthcare',
 'LoewCornell',
 'IRIDEX',
 'StratasysDirectManufacturing',
 'michaelfoods',
 'LundBoats',
 'TitanMachinery',
 'pbteen',
 'cebglobal',
 'CanonMJ',
 'NetApp',
 'bancosantander',
 'phl17',
 'Broadwind',
 'CATechnologies',
 'AdventuresbyDisney',
 'MealtimeMovement',
 'AtlanticCapital',
 'BerwickOffray',
 'sharecare',
 'FederalSignalFR',
 'Fox59News',
 'TKMaxxAustria',
 'SodaStream',
 'CogginOrangeParkBuickGMC',
 'AmericanRiverBank',
 'PortClintonNewsHerald',
 'proximityprague',
 'PolarisORV',
 'GoogleArtProject',
 'GranayMontero',
 'AccurayIncorporated',
 'RentACenter',
 'provenmethod',
 'Celanese',
 'NUKUSA',
 'ConcentrixCR',
 'PALbyLantronix',
 'Medaglia.dOro',
 'KBRincorporated',
 'MyriadGenetics',
 'ServiceMaster',
 'travelzoo',
 'WrightMedical',
 'peacecereal',
 'BlackRock',
 'YamanaGoldInc',
 'greenworks',
 'GarnierBBDO',
 'Allpoint.Network',
 'kumvtv',
 'BakerDist',
 'BradyNorthAmerica',
 'yourALLDATAteam',
 'sentrysafe',
 'heartlandrv',
 'BTUK',
 'Gartner',
 'godigitalmarketing',
 'maranathanutbutters',
 'Uncrustables',
 'sonomapharma',
 'hanoverinsurance',
 'ultragazoficial',
 'pgtwindowsdoors',
 'Kwittken',
 'elkodaily',
 'MarineMaxGrandLake',
 'RoofDepot',
 'nteloswireless',
 'NauticaUSA',
 'ING',
 'TakeShapeForLife',
 'scegnews',
 'MotorolaSolutions',
 'Gentherm',
 'Prudential',
 'hubspot',
 'Aussie',
 'ETSLindgren',
 'FederatedInvestors',
 'EternalArena',
 'DelWebbHomes',
 'HeraldDispatch',
 'mclartynissanlr',
 'HeadwayCapital',
 'KinderMorganInc',
 'HannibalCourierPost',
 'RidersByLee',
 'ComfortSystemsUsa',
 'WorldsofFun',
 'Danskin',
 'DarlingHomes',
 'AndrewMarcLeather',
 'avxcorp',
 'OCCSolutions',
 'ipass',
 'RoadrunnerTransportation',
 'FedEx',
 'DesMoinesRegister',
 'SherwinWilliamsforDesignersArchitects',
 'domtarpaper',
 'seaspine',
 'remax',
 'HealtheCareers',
 'MedtronicCareers',
 'stcloudtimes',
 'longhornsteakhouse',
 'arcdocumentsolutions',
 'SynnexShareTheMagic',
 'CambridgeChronicleIL',
 'belomedia',
 'RegionsBank',
 'Justenergyfoundation',
 'decbbdo',
 'safetyinsurance',
 'valleyfair',
 'demingheadlight',
 'ProDuoFrance',
 'suntrust',
 'KQCDtv',
 'VoyaFinancial',
 'Pioneerpump',
 'ElevateCredit',
 'NalleyLexusRoswell',
 'edaptmscompany',
 'LCNBNATBANK',
 'ktla5',
 'willisgroup',
 'cree',
 'petrovalveinc',
 'RFMDMedia',
 'blackbaud',
 'AllyBank',
 'CoreSite',
 'ThinkONSemiconductor',
 'braun',
 'swingline',
 'ConcentrixNI',
 'Enomcom',
 'pluralsight',
 'JohnDeereUSCA',
 '1stSourceBank',
 'plainscapital',
 'appcouples',
 'MithunAgency',
 'franklinfueling',
 'taeqoficial',
 'AvalonOrganics',
 'InterSalonSallyBeauty',
 'SusquehannaBank',
 'WorkspringChicago',
 'ResourcesGlobalProfessionals',
 'pagoda',
 'MilfordDailyNews',
 'thetimesnews',
 'OvaScience',
 'LivinLite',
 '99enterprises',
 'Smiths',
 'kuschall',
 'roselandresidentialtrust',
 'SOSClorox',
 'SKIIUS',
 'MoorMansShowTec',
 'alliedhealthgroup',
 'Resunate',
 'firstbankwyoming',
 'CogginBMWTreasureCoast',
 'newsleaderStaunton',
 'StJohnNewsKS',
 'cmlauncher',
 'AviatNet',
 'WOLVERINE',
 'mettlertoledo',
 'chevrolet',
 'AVLCitizenTimes',
 'BancorpSouthStudents',
 'muscatinejournal',
 'Oncolytics.Biotech.Inc',
 'VascularBiogenics',
 '1011News',
 'NukUSA',
 'TrapperKeepers',
 'goodneighborpharmacy',
 'mhelpdesk',
 'irobot',
 'OrtegaTacos',
 'ThorMotorCoach',
 'Salsa981',
 'HanfordSentinel',
 'clearfieldinc',
 'buyusedinventory',
 'Cerner',
 'FurnitureMedicCorporate',
 'WaynesvilleDailyGuide',
 'RiverviewBank',
 'IDenticardSystems',
 'McDonaldsUS',
 'jinkosolar',
 'NEWBlueSoHo',
 'POOLCORP',
 'DunBradstreet',
 'progresssw',
 'sincerelyinc',
 'catfootwear',
 'JASONPersonalCare',
 'autozone',
 'sandpglobal',
 'WhiteHouseBlackMarket',
 'rudisorganicbakery',
 'NyQuil.DayQuil',
 'SunbitesThailand',
 'cosmoprofbeauty',
 'farmerjohn',
 'exelis',
 'TheDowChemicalCompany',
 'CVGRP',
 'WashingtonTimesReporter',
 'BHS',
 'LincolnElectric',
 'foxsports',
 'GoogleDocs',
 'mtshastanews',
 'LaSuavecitaLasVegas',
 'CommVault',
 'NaEstradaComAIpiranga',
 'f5networksinc',
 'BankOfGreeneCounty',
 'barnesandnoble',
 'Cisco',
 'Dr.ReddysLaboratoriesLtd',
 'FirstFinancialBankNA',
 'lgstxservices',
 'aethlonmedical',
 'PCGSCOIN',
 'HomesteadWebsites',
 'chasebrass',
 'KILZBrand',
 'deprisa',
 'LinkedIn',
 'MrTire',
 'xfinity',
 'mcneilusconcrete',
 'PepsiUS',
 'WellingtonDailyNews',
 'carlislefsp',
 'brancomotores',
 'Activision',
 'EFI.Digital.Print.Technology',
 'therainbowcleaningsystem',
 'showtime',
 'LandstarSafety',
 'ServiceMasterClean',
 'beneficialbank',
 'Doubletree',
 'NalleyLexusGalleria',
 'kiterealtygroup',
 'SeacoastBank',
 'Cheetos',
 'cargurus',
 'Bongo',
 'bconnectedsocial',
 'hrblock',
 'chegg',
 'MandTBank',
 'lucy',
 'flextronicsintl',
 'AmegyBank',
 'CarpenterTech',
 'oshkoshcorporation',
 'FLIR',
 'HampshirePaper',
 'CallawayPreOwned',
 'VisteonCorporation',
 'Agrowsil',
 'towerjazz',
 'courierpost',
 'InnerWorkings',
 'FiveStarBankNY',
 'HaemoneticsCorp',
 'eWeekNews',
 'zimmer',
 'attunity',
 'BedBathAndBeyond',
 'HeartlandLuxuryHomes',
 'watchLOUD',
 'sunpower',
 'SoCoreEnergy',
 'eskycoolers',
 'SuperiorEnergy',
 'OnStrideFinancial',
 'Zillow',
 'iiviinc',
 'NVIDIA',
 'WestElm',
 'ProvidenceJournal',
 'nordsonmedical',
 'hormelvitalcuisine',
 'OwensCorningRoofingandAsphalt',
 'georgiaboot',
 'EAS',
 'witntv',
 'westfieldbankma',
 'EQTCorporation',
 'iSharesETFs',
 'AristaNW',
 'RAPPWORLDWIDE',
 'eatjaggers',
 'UnitedOnline1',
 'LaCroix',
 'SimulationsPlus',
 'cpbgroup',
 'Citrix',
 'PSAcard',
 'fauquierbank',
 'SailPoint',
 'popular',
 'BaxterInternationalInc',
 'yahoo',
 'generacpowersystems',
 'EatSmartVeggies',
 'hesscorporation',
 'diamondjodubuque',
 'Clorox',
 'toplasticsinc',
 'BoydGaming',
 'siftingsherald',
 'kidsfootlocker',
 'usanahealthsciences',
 'Norwegiancruiseline',
 'ScholasticBookClubs',
 'thrushexhaust',
 'disneylandparis',
 'AppianCorporation',
 'jet',
 'bonefishgrill',
 'SnapNamesDotCom',
 'microbotmedical',
 'GameStopDACH',
 'DEWALT',
 'otiGlobal',
 'WheelerREIT',
 'OlinCareers',
 'GeneralDynamicsIT',
 'rushtruckcenters',
 'MercuryComputerSystems',
 'Internap',
 'TwoRiverCommunityBank',
 'lowes',
 'americanaxle',
 'carters',
 'MasterLock',
 'charmin',
 'Southwest',
 'wayfair',
 'littleburgundyshoes',
 'realfacesofdairy',
 'Alarmdotcom',
 'troveapp',
 'StandardBrandParts',
 'marinemaxlaketexomahighportmarina',
 'ParADice',
 'henryschein',
 'spcapitaliq',
 'Journeys',
 'fox6news',
 'aldiadallas',
 'vailmtn',
 'potterybarn',
 'TandbergData',
 'ParatekPharma',
 'officialmmajunkie',
 'imaginesoups',
 'SabreCorporation',
 'Phillips66Co',
 'smithwessoncorp',
 'VlasicStork',
 'InformationServicesGroup',
 'northwest',
 'GaliciaSeguros',
 'RnDSystems',
 'fusionconnect',
 'TimHortonsUS',
 'UGGAustralia',
 'FifthThirdBank',
 'Luxoft',
 'Insperity',
 'Jose1071.1FM',
 'Cutera',
 'LauraScuddersPeanutButter',
 'HMHTeen',
 'PKUcom',
 'colemanusa',
 'Underarmour',
 'sprint',
 'risecredit',
 'ChillicotheTimesBulletin',
 'EnergyFocusInc',
 'Macys',
 'Carrabbas',
 'SAP',
 'AquaticaTexas',
 'GreenDot',
 'AppliedMaterialsInc',
 'GNCLiveWell',
 'Bojangles',
 'lifetimefitness',
 'Delawareonline',
 'durangoboot',
 'SeaWorld',
 'ameliabellecasino',
 'AmericanExpressUS',
 'campaigneremail',
 'GrandmasMolasses',
 'ULTA',
 'control4fans',
 'boingo',
 'scholasticparents',
 ...}

In [25]:
ln[ln["company_name"].isin(inter)]["industry"].nunique()

79

In [24]:
ln[ln["company_name"].isin(inter)]["industry"].unique()

array(['Information Technology and Services', 'Computer Networking',
       'Electrical/Electronic Manufacturing', 'Internet',
       'Mechanical or Industrial Engineering', 'Oil & Energy', 'Retail',
       'Financial Services', 'Pharmaceuticals', 'Wireless',
       'Computer Software', 'Banking', 'Computer Games',
       'Food & Beverages', 'Defense & Space', 'Chemicals', 'Insurance',
       'Restaurants', 'Package/Freight Delivery', 'Construction',
       'Utilities', 'Automotive', 'Information Services',
       'Facilities Services', 'Entertainment', 'Real Estate',
       'Human Resources', 'Food Production', 'Computer Hardware',
       'Computer & Network Security', 'Medical Devices',
       'Health, Wellness and Fitness', 'Telecommunications',
       'Semiconductors', 'Consumer Goods', nan, 'Consumer Electronics',
       'Biotechnology', 'Hospital & Health Care', 'Music',
       'Management Consulting', 'E-Learning',
       'Security and Investigations', 'Consumer Services', 'Cosmetics',
       'Education Management', 'Online Media', 'Outsourcing/Offshoring',
       'Defense &amp; Space', 'Law Enforcement',
       'Hospital &amp; Health Care', 'Oil &amp; Energy',
       'Computer &amp; Network Security', 'Food &amp; Beverages',
       'Airlines/Aviation', 'Renewables &amp; Environment',
       'Renewables & Environment', 'Wholesale', 'Legal Services',
       'Aviation &amp; Aerospace', 'Furniture', 'Mining &amp; Metals',
       'Hospitality', 'Printing', 'Staffing and Recruiting', 'Warehousing',
       'Higher Education', 'Motion Pictures and Film',
       'Marketing and Advertising', 'Aviation & Aerospace',
       'Mining & Metals', 'Building Materials', 'Environmental Services',
       'Publishing', 'Textiles', 'Machinery', 'Apparel & Fashion',
       'Design', 'Sporting Goods', 'Professional Training & Coaching'], dtype=object)

In [26]:
ln.corr()

,dataset_id,followers_count,employees_on_platform,entity_id,cusip,isin
dataset_id,1.000000,-0.235928,-0.272374,NaN,NaN,NaN
followers_count,-0.235928,1.000000,0.729740,NaN,NaN,NaN
employees_on_platform,-0.272374,0.729740,1.000000,NaN,NaN,NaN
entity_id,NaN,NaN,NaN,NaN,NaN,NaN
cusip,NaN,NaN,NaN,NaN,NaN,NaN
isin,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
jb.head()

In [40]:
ln.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2426196 entries, 0 to 2426195
Data columns (total 14 columns):
dataset_id               int64
as_of_date               object
company_name             object
followers_count          int64
employees_on_platform    int64
link                     object
industry                 object
date_added               object
date_updated             object
description              object
website                  object
entity_id                float64
cusip                    float64
isin                     float64
dtypes: float64(3), int64(3), object(8)
memory usage: 259.1+ MB

In [46]:
a=ln["company_name"].unique()
b= fb["username"].unique()

In [48]:
len(set(a)-set(b))

4782

In [53]:
r={1,2}
r.intersection

In [55]:
len(set(a).intersection(set(b)))

246

In [3]:
fb=pd.read_csv("temp_datalab_records_social_facebook.csv")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
fb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3621391 entries, 0 to 3621390
Data columns (total 14 columns):
dataset_id             int64
time                   object
username               object
checkins               int64
has_added_app          object
were_here_count        int64
likes                  int64
talking_about_count    int64
facebook_id            int64
date_added             object
date_updated           object
entity_id              float64
cusip                  float64
isin                   float64
dtypes: float64(3), int64(6), object(5)
memory usage: 386.8+ MB

In [42]:
fb["username"].nunique()

4950

In [38]:
fb.corr()

,dataset_id,checkins,were_here_count,likes,talking_about_count,facebook_id,entity_id,cusip,isin
dataset_id,1.000000,0.014284,-0.033538,-0.047131,-0.031880,0.117912,NaN,NaN,NaN
checkins,0.014284,1.000000,0.166944,0.052411,0.038259,-0.020870,NaN,NaN,NaN
were_here_count,-0.033538,0.166944,1.000000,0.256956,0.065495,0.077585,NaN,NaN,NaN
likes,-0.047131,0.052411,0.256956,1.000000,0.358866,0.039388,NaN,NaN,NaN
talking_about_count,-0.031880,0.038259,0.065495,0.358866,1.000000,-0.037722,NaN,NaN,NaN
facebook_id,0.117912,-0.020870,0.077585,0.039388,-0.037722,1.000000,NaN,NaN,NaN
entity_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cusip,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
isin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
fb.were_here_count.unique()

array([      0,     173,   46288, ...,  103379,  134857, 2976251], dtype=int64)

In [18]:
fb.time.head()[0]

'2015-01-01 05:00:00+00'

In [15]:
fb.groupby(["username", "time"])[]

In [27]:
datetime.time()

TypeError: descriptor 'time' of 'datetime.datetime' object needs an argument